<?php /** @var DataFeedWatch_Connector_Block_Adminhtml_System_Config_Grid_Pager $this */ ?>
<span class="inheritance_pager">
    <span class="page">
    <?php echo $this->helper('adminhtml')->__('Page') ?>

        <?php $currentPage = $this->getPage() ?>
        <?php $currentLimit = $this->getLimit() ?>
        <?php $lastPage = $this->getCollection()->getLastPageNumber() ?>
        <?php if($currentPage > 1): ?>
            <a href="#" title="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Previous page')) ?>"
               onclick="getInheritanceGrid(<?php echo sprintf('%d, %d', $currentPage - 1, $currentLimit) ?>);return false;" >
                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left.gif') ?>"
                     alt="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Go to Previous page')) ?>" class="arrow navigation"/>
            </a>
        <?php else: ?>
            <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left_off.gif') ?>"
                 alt="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Go to Previous page')) ?>" class="arrow navigation"/>
        <?php endif; ?>

        <input type="text" name="page" value="<?php echo $currentPage ?>" class="input-text page"
               onkeyup="getInheritanceGrid(this.value, <?php echo $currentLimit ?>)" />


        <?php if($currentPage < $lastPage): ?>
            <a href="#" title="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Next page')) ?>"
               onclick="getInheritanceGrid(<?php echo sprintf('%d, %d', $currentPage + 1, $currentLimit) ?>);return false;" >
                <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right.gif') ?>"
                     alt="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Go to Next page')) ?>" class="arrow navigation"/>
            </a>
        <?php else: ?>
            <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right_off.gif') ?>"
                 alt="<?php echo Mage::helper('core')->quoteEscape($this->helper('adminhtml')->__('Go to Next page')) ?>" class="arrow navigation"/>
        <?php endif; ?>

        <?php echo $this->helper('adminhtml')->__('of %s pages', $this->getCollection()->getLastPageNumber()) ?>
    </span>
    <span class="limit">
    <?php echo $this->helper('adminhtml')->__('View') ?>
        <select name="limit" onchange="getInheritanceGrid(<?php echo $currentPage ?>, this.value)">
            <option value="5"<?php if($this->getCollection()->getPageSize()==5): ?> selected="selected"<?php endif; ?>>5</option>
            <option value="10"<?php if($this->getCollection()->getPageSize()==10): ?> selected="selected"<?php endif; ?>>10</option>
            <option value="20"<?php if($this->getCollection()->getPageSize()==20): ?> selected="selected"<?php endif; ?>>20</option>
            <option value="50"<?php if($this->getCollection()->getPageSize()==50): ?> selected="selected"<?php endif; ?>>50</option>
            <option value="100"<?php if($this->getCollection()->getPageSize()==100): ?> selected="selected"<?php endif; ?>>100</option>
            <option value="200"<?php if($this->getCollection()->getPageSize()==200): ?> selected="selected"<?php endif; ?>>200</option>
            <option value="500"<?php if($this->getCollection()->getPageSize()==500): ?> selected="selected"<?php endif; ?>>500</option>
        </select>
        <?php echo $this->helper('adminhtml')->__('per page') ?>
    </span>
    <span class="total_of">
    <?php echo $this->helper('adminhtml')->__('Total %d records found', $this->getCollection()->getSize()) ?>
        <span id="dfw_grid_inheritance_total_count" class="no-display"><?php echo $this->getCollection()->getSize() ?></span>
    </span>
</span>